// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ConsoleScreen = NULL;
// event funtions
void ui_event_ConsoleScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
        LVGL_Console_exit_function(e);
    }
}

// build funtions

void ui_ConsoleScreen_screen_init(void)
{
    ui_ConsoleScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConsoleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConsoleScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConsoleScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConsoleScreen, ui_event_ConsoleScreen, LV_EVENT_ALL, NULL);

}

void ui_ConsoleScreen_screen_destroy(void)
{
    if(ui_ConsoleScreen) lv_obj_del(ui_ConsoleScreen);

    // NULL screen variables
    ui_ConsoleScreen = NULL;

}
