// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CONSOLESCREEN_H
#define UI_CONSOLESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConsoleScreen
extern void ui_ConsoleScreen_screen_init(void);
extern void ui_ConsoleScreen_screen_destroy(void);
extern void ui_event_ConsoleScreen(lv_event_t * e);
extern lv_obj_t * ui_ConsoleScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

