// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LISTSCREEN_H
#define UI_LISTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ListScreen
extern void ui_ListScreen_screen_init(void);
extern void ui_ListScreen_screen_destroy(void);
extern lv_obj_t * ui_ListScreen;
extern void ui_event_ListExitPanel(lv_event_t * e);
extern lv_obj_t * ui_ListExitPanel;
extern lv_obj_t * ui_Title;
extern lv_obj_t * ui_ListContainer;
extern void ui_event_MemberPanel(lv_event_t * e);
extern lv_obj_t * ui_MemberPanel;
extern lv_obj_t * ui_MemberName;
extern lv_obj_t * ui_MemberType;
extern lv_obj_t * ui_MemberState;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

