// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ListScreen = NULL;
lv_obj_t * ui_ListExitPanel = NULL;
lv_obj_t * ui_Title = NULL;
lv_obj_t * ui_ListContainer = NULL;
lv_obj_t * ui_MemberPanel = NULL;
lv_obj_t * ui_MemberName = NULL;
lv_obj_t * ui_MemberType = NULL;
lv_obj_t * ui_MemberState = NULL;
// event funtions
void ui_event_ListExitPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_MemberPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LVGL_ListMember_event_function(e);
    }
}

// build funtions

void ui_ListScreen_screen_init(void)
{
    ui_ListScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ListScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ListScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ListScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ListExitPanel = lv_obj_create(ui_ListScreen);
    lv_obj_set_width(ui_ListExitPanel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ListExitPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ListExitPanel, 50);
    lv_obj_set_y(ui_ListExitPanel, 10);
    lv_obj_clear_flag(ui_ListExitPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ListExitPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ListExitPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ListExitPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ListExitPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Title = lv_label_create(ui_ListExitPanel);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title, "DeviceList");
    lv_obj_set_style_text_color(ui_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ListContainer = lv_obj_create(ui_ListScreen);
    lv_obj_remove_style_all(ui_ListContainer);
    lv_obj_set_width(ui_ListContainer, 384);
    lv_obj_set_height(ui_ListContainer, 320);
    lv_obj_set_x(ui_ListContainer, 0);
    lv_obj_set_y(ui_ListContainer, 63);
    lv_obj_clear_flag(ui_ListContainer, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_MemberPanel = lv_obj_create(ui_ListContainer);
    lv_obj_set_width(ui_MemberPanel, 384);
    lv_obj_set_height(ui_MemberPanel, 80);
    lv_obj_clear_flag(ui_MemberPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MemberPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MemberPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MemberPanel, lv_color_hex(0x0F0F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MemberPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MemberPanel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MemberName = lv_label_create(ui_MemberPanel);
    lv_obj_set_width(ui_MemberName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MemberName, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_MemberName, "MemberName");
    lv_obj_set_style_text_color(ui_MemberName, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MemberName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MemberName, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MemberType = lv_label_create(ui_MemberPanel);
    lv_obj_set_width(ui_MemberType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MemberType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MemberType, 0);
    lv_obj_set_y(ui_MemberType, 5);
    lv_obj_set_align(ui_MemberType, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_MemberType, "MemberType");
    lv_obj_set_style_text_color(ui_MemberType, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MemberType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MemberType, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MemberState = lv_label_create(ui_MemberPanel);
    lv_obj_set_width(ui_MemberState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MemberState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MemberState, 16);
    lv_obj_set_y(ui_MemberState, 0);
    lv_obj_set_align(ui_MemberState, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_MemberState, "MemberState");
    lv_obj_set_style_text_color(ui_MemberState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MemberState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MemberState, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ListExitPanel, ui_event_ListExitPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MemberPanel, ui_event_MemberPanel, LV_EVENT_ALL, NULL);

}

void ui_ListScreen_screen_destroy(void)
{
    if(ui_ListScreen) lv_obj_del(ui_ListScreen);

    // NULL screen variables
    ui_ListScreen = NULL;
    ui_ListExitPanel = NULL;
    ui_Title = NULL;
    ui_ListContainer = NULL;
    ui_MemberPanel = NULL;
    ui_MemberName = NULL;
    ui_MemberType = NULL;
    ui_MemberState = NULL;

}
