// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern void ui_event_WIFIButton(lv_event_t * e);
extern lv_obj_t * ui_WIFIButton;
extern lv_obj_t * ui_WLANName;
extern void ui_event_WLANSwitch(lv_event_t * e);
extern lv_obj_t * ui_WLANSwitch;
extern lv_obj_t * ui_WLANlogPNG;
extern void ui_event_BluetoothButton(lv_event_t * e);
extern lv_obj_t * ui_BluetoothButton;
extern lv_obj_t * ui_BluetoothName;
extern lv_obj_t * ui_BluetoothSwitch;
extern lv_obj_t * ui_BLlogPNG;
extern void ui_event_BatteryButton(lv_event_t * e);
extern lv_obj_t * ui_BatteryButton;
extern lv_obj_t * ui_BatteryName;
extern void ui_event_BatterySwitch(lv_event_t * e);
extern lv_obj_t * ui_BatterySwitch;
extern lv_obj_t * ui_BatterylogPNG;
extern void ui_event_CloudSyncButton(lv_event_t * e);
extern lv_obj_t * ui_CloudSyncButton;
extern lv_obj_t * ui_Cloud_Sync;
extern void ui_event_CloudSyncSwitch(lv_event_t * e);
extern lv_obj_t * ui_CloudSyncSwitch;
extern lv_obj_t * ui_CloudSyncPNG;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

