// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_timelabel = NULL;
lv_obj_t * ui_dataLabel = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timelabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timelabel, 116);
    lv_obj_set_y(ui_timelabel, 100);
    lv_label_set_text(ui_timelabel, "00:00:00");
    lv_obj_set_style_text_color(ui_timelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timelabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dataLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_dataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dataLabel, 116);
    lv_obj_set_y(ui_dataLabel, 66);
    lv_label_set_text(ui_dataLabel, "2025/10/12");
    lv_obj_set_style_text_color(ui_dataLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dataLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dataLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_timelabel = NULL;
    ui_dataLabel = NULL;

}
