// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_WIFIButton = NULL;
lv_obj_t * ui_WLANName = NULL;
lv_obj_t * ui_WLANSwitch = NULL;
lv_obj_t * ui_WLANlogPNG = NULL;
lv_obj_t * ui_BluetoothButton = NULL;
lv_obj_t * ui_BluetoothName = NULL;
lv_obj_t * ui_BluetoothSwitch = NULL;
lv_obj_t * ui_BLlogPNG = NULL;
lv_obj_t * ui_BatteryButton = NULL;
lv_obj_t * ui_BatteryName = NULL;
lv_obj_t * ui_BatterySwitch = NULL;
lv_obj_t * ui_BatterylogPNG = NULL;
lv_obj_t * ui_CloudSyncButton = NULL;
lv_obj_t * ui_Cloud_Sync = NULL;
lv_obj_t * ui_CloudSyncSwitch = NULL;
lv_obj_t * ui_CloudSyncPNG = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_WIFIButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ListScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ListScreen_screen_init);
        LVGL_WIFI_List_event_function(e);
    }
}

void ui_event_WLANSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        LVGL_WIFI_SWevent_function(e);
    }
}

void ui_event_BluetoothButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ListScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ListScreen_screen_init);
    }
}

void ui_event_BatteryButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConsoleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 2, 0, &ui_ConsoleScreen_screen_init);
        LVGL_Console_enter_function(e);
    }
}

void ui_event_BatterySwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        LVGL_PMIC_SWevent_function(e);
    }
}

void ui_event_CloudSyncButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConsoleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 16, 0, &ui_ConsoleScreen_screen_init);
        LVGL_Cloud_Sync_function(e);
    }
}

void ui_event_CloudSyncSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        LVGL_Sync_SWevent_function(e);
        _ui_screen_change(&ui_ConsoleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 16, 16, &ui_ConsoleScreen_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(ui_Screen2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_WIFIButton, 320);
    lv_obj_set_height(ui_WIFIButton, 120);
    lv_obj_set_x(ui_WIFIButton, 63);
    lv_obj_set_y(ui_WIFIButton, 32);
    lv_obj_add_flag(ui_WIFIButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WIFIButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WIFIButton, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WIFIButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WIFIButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WIFIButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WIFIButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_WLANName = lv_label_create(ui_WIFIButton);
    lv_obj_set_width(ui_WLANName, 160);
    lv_obj_set_height(ui_WLANName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WLANName, 48);
    lv_obj_set_y(ui_WLANName, 0);
    lv_obj_set_align(ui_WLANName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WLANName, "WLAN");
    lv_obj_set_style_text_font(ui_WLANName, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WLANSwitch = lv_switch_create(ui_WIFIButton);
    lv_obj_set_width(ui_WLANSwitch, 100);
    lv_obj_set_height(ui_WLANSwitch, 100);
    lv_obj_set_align(ui_WLANSwitch, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_WLANSwitch, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WLANSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WLANSwitch, lv_color_hex(0x323232), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WLANSwitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WLANSwitch, lv_color_hex(0x1A80CC), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WLANSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_WLANSwitch, lv_color_hex(0x323232), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WLANSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WLANSwitch, lv_color_hex(0x1A80CC), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WLANSwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_WLANlogPNG = lv_img_create(ui_WLANSwitch);
    lv_img_set_src(ui_WLANlogPNG, &ui_img_wifi64_png);
    lv_obj_set_width(ui_WLANlogPNG, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_WLANlogPNG, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_WLANlogPNG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WLANlogPNG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WLANlogPNG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BluetoothButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BluetoothButton, 320);
    lv_obj_set_height(ui_BluetoothButton, 120);
    lv_obj_set_x(ui_BluetoothButton, 63);
    lv_obj_set_y(ui_BluetoothButton, 184);
    lv_obj_add_flag(ui_BluetoothButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BluetoothButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BluetoothButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BluetoothButton, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluetoothButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BluetoothButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BluetoothButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BluetoothButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BluetoothButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BluetoothName = lv_label_create(ui_BluetoothButton);
    lv_obj_set_width(ui_BluetoothName, 160);
    lv_obj_set_height(ui_BluetoothName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BluetoothName, 48);
    lv_obj_set_y(ui_BluetoothName, 0);
    lv_obj_set_align(ui_BluetoothName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BluetoothName, "Bluetooth");
    lv_obj_set_style_text_font(ui_BluetoothName, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BluetoothSwitch = lv_switch_create(ui_BluetoothButton);
    lv_obj_set_width(ui_BluetoothSwitch, 100);
    lv_obj_set_height(ui_BluetoothSwitch, 100);
    lv_obj_set_align(ui_BluetoothSwitch, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_BluetoothSwitch, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluetoothSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BluetoothSwitch, lv_color_hex(0x323232), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluetoothSwitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BluetoothSwitch, lv_color_hex(0x1A80CC), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BluetoothSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_BluetoothSwitch, lv_color_hex(0x323232), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluetoothSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BluetoothSwitch, lv_color_hex(0x1A80CC), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BluetoothSwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_BLlogPNG = lv_img_create(ui_BluetoothSwitch);
    lv_img_set_src(ui_BLlogPNG, &ui_img_bluetooth64_png);
    lv_obj_set_width(ui_BLlogPNG, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_BLlogPNG, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_BLlogPNG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLlogPNG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BLlogPNG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BatteryButton, 320);
    lv_obj_set_height(ui_BatteryButton, 120);
    lv_obj_set_x(ui_BatteryButton, 63);
    lv_obj_set_y(ui_BatteryButton, 336);
    lv_obj_add_flag(ui_BatteryButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BatteryButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BatteryButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryButton, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BatteryButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BatteryButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BatteryButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BatteryName = lv_label_create(ui_BatteryButton);
    lv_obj_set_width(ui_BatteryName, 160);
    lv_obj_set_height(ui_BatteryName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryName, 48);
    lv_obj_set_y(ui_BatteryName, 0);
    lv_obj_set_align(ui_BatteryName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryName, "Battery");
    lv_obj_set_style_text_font(ui_BatteryName, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatterySwitch = lv_switch_create(ui_BatteryButton);
    lv_obj_set_width(ui_BatterySwitch, 100);
    lv_obj_set_height(ui_BatterySwitch, 100);
    lv_obj_set_align(ui_BatterySwitch, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_BatterySwitch, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatterySwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BatterySwitch, lv_color_hex(0x323232), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatterySwitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatterySwitch, lv_color_hex(0x1A80CC), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BatterySwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_BatterySwitch, lv_color_hex(0x323232), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatterySwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatterySwitch, lv_color_hex(0x1A80CC), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BatterySwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_BatterylogPNG = lv_img_create(ui_BatterySwitch);
    lv_img_set_src(ui_BatterylogPNG, &ui_img_battery64_png);
    lv_obj_set_width(ui_BatterylogPNG, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_BatterylogPNG, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_BatterylogPNG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatterylogPNG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatterylogPNG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CloudSyncButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_CloudSyncButton, 320);
    lv_obj_set_height(ui_CloudSyncButton, 120);
    lv_obj_set_x(ui_CloudSyncButton, 63);
    lv_obj_set_y(ui_CloudSyncButton, 488);
    lv_obj_add_flag(ui_CloudSyncButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CloudSyncButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CloudSyncButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CloudSyncButton, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CloudSyncButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CloudSyncButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CloudSyncButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CloudSyncButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CloudSyncButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Cloud_Sync = lv_label_create(ui_CloudSyncButton);
    lv_obj_set_width(ui_Cloud_Sync, 160);
    lv_obj_set_height(ui_Cloud_Sync, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cloud_Sync, 48);
    lv_obj_set_y(ui_Cloud_Sync, 0);
    lv_obj_set_align(ui_Cloud_Sync, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Cloud_Sync, "Cloud Sync");
    lv_obj_set_style_text_font(ui_Cloud_Sync, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CloudSyncSwitch = lv_switch_create(ui_CloudSyncButton);
    lv_obj_set_width(ui_CloudSyncSwitch, 100);
    lv_obj_set_height(ui_CloudSyncSwitch, 100);
    lv_obj_set_align(ui_CloudSyncSwitch, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_CloudSyncSwitch, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CloudSyncSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CloudSyncSwitch, lv_color_hex(0x323232), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CloudSyncSwitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CloudSyncSwitch, lv_color_hex(0x1A80CC), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CloudSyncSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_CloudSyncSwitch, lv_color_hex(0x323232), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CloudSyncSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CloudSyncSwitch, lv_color_hex(0x1A80CC), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CloudSyncSwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_CloudSyncPNG = lv_img_create(ui_CloudSyncSwitch);
    lv_img_set_src(ui_CloudSyncPNG, &ui_img_334164688);
    lv_obj_set_width(ui_CloudSyncPNG, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_CloudSyncPNG, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_CloudSyncPNG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CloudSyncPNG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CloudSyncPNG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_WLANSwitch, ui_event_WLANSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WIFIButton, ui_event_WIFIButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BluetoothButton, ui_event_BluetoothButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BatterySwitch, ui_event_BatterySwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BatteryButton, ui_event_BatteryButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CloudSyncSwitch, ui_event_CloudSyncSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CloudSyncButton, ui_event_CloudSyncButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_WIFIButton = NULL;
    ui_WLANName = NULL;
    ui_WLANSwitch = NULL;
    ui_WLANlogPNG = NULL;
    ui_BluetoothButton = NULL;
    ui_BluetoothName = NULL;
    ui_BluetoothSwitch = NULL;
    ui_BLlogPNG = NULL;
    ui_BatteryButton = NULL;
    ui_BatteryName = NULL;
    ui_BatterySwitch = NULL;
    ui_BatterylogPNG = NULL;
    ui_CloudSyncButton = NULL;
    ui_Cloud_Sync = NULL;
    ui_CloudSyncSwitch = NULL;
    ui_CloudSyncPNG = NULL;

}
