// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "WIFI.h"
#include "light_sleep.h"
#include "OTA.h"
#include "panel.h"
void LVGL_WIFI_SWevent_function(lv_event_t * e)
{
	// Your code here
	if (e == NULL) {
        return;
    }

    lv_obj_t *sw = lv_event_get_target(e);
    if (sw == NULL) {
        return;
    }

    bool is_on = lv_obj_has_state(sw, LV_STATE_CHECKED);

    if (is_on) {
        WIFI_init();
        if (ui_WLANName) {
            lv_label_set_text(ui_WLANName, "WLAN ON");
        }
    } else {
        WIFI_deinit();
        if (ui_WLANName) {
            lv_label_set_text(ui_WLANName, "WLAN OFF");
        }
        // if (ui_DeviceListPanel) {
        //     lv_obj_add_flag(ui_DeviceListPanel, LV_OBJ_FLAG_HIDDEN);
        // }
    }
}

void LVGL_WIFI_List_event_function(lv_event_t * e)
{
	// Your code here
    lv_label_set_text(ui_Title, "WLAN List");
    TaskHandle_t current_task = xTaskGetCurrentTaskHandle();

    wifi_cmd_scan_params_t scan_cfg = {
        .target_ssid      = "",
        .target_channel   = 0,
        .show_hidden      = true,
        .scan_time_min_ms = 120,
        .scan_time_max_ms = 300,
    };

    WIFI_send_cmd(WIFI_CMD_SCAN, &scan_cfg, current_task, 0);
}

void LVGL_ListExit_event_function(lv_event_t * e)
{
	// Your code here
    TaskHandle_t current_task = xTaskGetCurrentTaskHandle();
    wifi_cmd_monitor_params_t monitor_cfg = {0};
    WIFI_send_cmd(WIFI_CMD_MONITOR_STOP, &monitor_cfg, current_task, 0);
}


void LVGL_ListMember_event_function(lv_event_t * e)
{
	// Your code here
    lv_obj_t *panel = lv_event_get_target(e);
    if (panel == NULL)  return;

    /* 从被点击面板的第一子对象 (SSID label) 提取 SSID */
    if (lv_obj_get_child_cnt(panel) < 1)  return;

    lv_obj_t *name_label = lv_obj_get_child(panel, 0);
    const char *ssid = lv_label_get_text(name_label);

    TaskHandle_t current_task = xTaskGetCurrentTaskHandle();

    wifi_cmd_monitor_params_t monitor_cfg = {0};
    monitor_cfg.target_channel = 0;
    if (ssid != NULL) {
        strncpy(monitor_cfg.target_ssid, ssid, SSID_MAX_LEN - 1);
        monitor_cfg.target_ssid[SSID_MAX_LEN - 1] = '\0';
    }
    WIFI_send_cmd(WIFI_CMD_MONITOR_START, &monitor_cfg, current_task, 0);
    lv_label_set_text(ui_Title, "STA List");
}

void LVGL_PMIC_SWevent_function(lv_event_t * e)
{
	// Your code here
    if (e == NULL) {
        return;
    }

    lv_obj_t *sw = lv_event_get_target(e);
    if (sw == NULL) {
        return;
    }

    bool is_on = lv_obj_has_state(sw, LV_STATE_CHECKED);

    if (is_on) {
        enter_lightsleep = true;
    } else {

    }
}

void LVGL_PMIC_monitor_function(lv_event_t * e)
{
	// Your code here
    uint32_t trigger = 0xFFFFFFFF;
    xQueueSend(pmic_event_queue, &trigger, 0);
}

void LVGL_Console_exit_function(lv_event_t * e)
{
	// Your code here
    uint32_t trigger = 0;
    xQueueSend(pmic_event_queue, &trigger, 0);
    AMOLED_console_log(INFORM, false, "ui" ,"CONSOLE_DISPLAY_DISABLE");
    AMOLED_refresh();
}

void LVGL_Cloud_Sync_function(lv_event_t * e)
{
	// Your code here
    AMOLED_console_log(INFORM, false, "ui" ,"CONSOLE_DISPLAY_ENABLE");
}

static TaskHandle_t s_ota_task_handle = NULL;

void LVGL_Sync_SWevent_function(lv_event_t * e)
{
	// Your code here
    if (e == NULL) {
        return;
    }

    lv_obj_t *sw = lv_event_get_target(e);
    if (sw == NULL) {
        return;
    }

    bool is_on = lv_obj_has_state(sw, LV_STATE_CHECKED);

    if (is_on) {
        if (s_ota_task_handle == NULL) {
            BaseType_t ret = xTaskCreate(&task_ota, "task_ota", 8192, NULL, 5, &s_ota_task_handle);
            AMOLED_console_log(INFORM, false, "ui" ,"CONSOLE_DISPLAY_ENABLE");
            if (ret != pdPASS) {
                AMOLED_console_log(ERROR, false, "ui", "Failed to create OTA task");
            }
        }
    } else {
        AMOLED_console_log(INFORM, false, "ui" ,"CONSOLE_DISPLAY_ENABLE");
        if (s_ota_task_handle != NULL) {
            OTA_request_cancel();
            s_ota_task_handle = NULL;
        }
    }
}
