// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "WIFI.h"
#include "light_sleep.h"
#include "panel.h"
void LVGL_WIFI_SWevent_function(lv_event_t * e)
{
	// Your code here
	if (e == NULL) {
        return;
    }

    lv_obj_t *sw = lv_event_get_target(e);
    if (sw == NULL) {
        return;
    }

    bool is_on = lv_obj_has_state(sw, LV_STATE_CHECKED);

    if (is_on) {
        /* Step 1: 打开 WiFi STA（内部应为幂等，重复调用无副作用） */
        WIFI_init();

        /* Step 2: UI 反馈（可选） */
        if (ui_WLANName) {
            lv_label_set_text(ui_WLANName, "WLAN ON");
        }
    } else {
        /* Step 3: 关闭 WiFi STA 并释放资源 */
        WIFI_STA_deinit();

        /* Step 4: UI 反馈（可选） */
        if (ui_WLANName) {
            lv_label_set_text(ui_WLANName, "WLAN OFF");
        }
        // if (ui_DeviceListPanel) {
        //     lv_obj_add_flag(ui_DeviceListPanel, LV_OBJ_FLAG_HIDDEN);
        // }
    }
}

void LVGL_PMIC_SWevent_function(lv_event_t * e)
{
	// Your code here
    if (e == NULL) {
        return;
    }

    lv_obj_t *sw = lv_event_get_target(e);
    if (sw == NULL) {
        return;
    }

    bool is_on = lv_obj_has_state(sw, LV_STATE_CHECKED);

    if (is_on) {
        enter_lightsleep = true;
    } else {

    }
}

void LVGL_WIFI_List_event_function(lv_event_t * e)
{
	// Your code here
    TaskHandle_t current_task = xTaskGetCurrentTaskHandle();

    wifi_cmd_scan_params_t scan_cfg = {
        .target_ssid      = "",
        .target_channel   = 0,
        .show_hidden      = true,
        .scan_time_min_ms = 120,
        .scan_time_max_ms = 300,
    };

    WIFI_send_cmd(WIFI_CMD_SCAN, &scan_cfg, current_task, 0);
}

void LVGL_ListMember_event_function(lv_event_t * e)
{
	// Your code here
}

void LVGL_Console_enter_function(lv_event_t * e)
{
	// Your code here
    vTaskDelay(50);
    AMOLED_console_log(INFORM, false, "ui" ,"CONSOLE_DISPLAY_ENABLE");
    // uint8_t target_ap_mac[6] = {0x90, 0x0F, 0x0C, 0xC7, 0xC2, 0xBF};
    // WIFI_deauth_attack(target_ap_mac, 0x0002);
}

void LVGL_Console_exit_function(lv_event_t * e)
{
	// Your code here
    AMOLED_console_log(INFORM, false, "ui" ,"CONSOLE_DISPLAY_DISABLE");
}
