// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LVGL_WIFI_List_event_function(lv_event_t * e);
void LVGL_WIFI_SWevent_function(lv_event_t * e);
void LVGL_Console_enter_function(lv_event_t * e);
void LVGL_PMIC_SWevent_function(lv_event_t * e);
void LVGL_ListMember_event_function(lv_event_t * e);
void LVGL_Console_exit_function(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
