// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_WLAN_H
#define _UI_COMP_WLAN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT WLAN
#define UI_COMP_WLAN_WLAN 0
#define _UI_COMP_WLAN_NUM 1
lv_obj_t * ui_WLAN_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
