// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT WLAN

lv_obj_t * ui_WLAN_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_WLAN;
    cui_WLAN = lv_label_create(comp_parent);
    lv_obj_set_width(cui_WLAN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_WLAN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_WLAN, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_WLAN_NUM);
    children[UI_COMP_WLAN_WLAN] = cui_WLAN;
    lv_obj_add_event_cb(cui_WLAN, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_WLAN, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_WLAN_create_hook(cui_WLAN);
    return cui_WLAN;
}

